apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission-webhook-cfg
  labels:
    app: mutating-admission-webhook
webhooks:
  - name: mutate.stampy.data.sfdc.net
    clientConfig:
      service:
        name: stampy-admission-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    #namespaceSelector:
    #  matchLabels:
    #    stampy-admission-webhook: enabled

